# Video wallpaper automated regression suite (Phase 8).
# Prerequisites: build/YumeirenTest.exe built; test media under build/media/video
# (perf_switch*.mp4, inv/*.mp4, generated by docs/perf + this repo's tooling).
# Each test: launch unelevated YumeirenTest via HKCU settings (same as perf tooling),
# sample metrics with sample2.ps1, evaluate pass criteria from the CSV.
# System-event scenarios (lock/unlock/sleep/explorer restart/dual screen) are NOT
# automatable here - see README.md manual checklist.
param(
    [string]$Exe = "C:\Users\rain\Documents\ExplorerBg\FolderBgStudio\build\YumeirenTest.exe",
    [string]$MediaRoot = "C:\Users\rain\Documents\ExplorerBg\FolderBgStudio\build\media\video",
    [string]$OutDir = "C:\Users\rain\Documents\ExplorerBg\FolderBgStudio\tools\perf\results",
    [string]$DiagLog = "$env:LOCALAPPDATA\Yumeiren\logs\videowallpaper.log"
)
$ErrorActionPreference = "Continue"
$runAwake = "C:\Users\rain\Documents\ExplorerBg\FolderBgStudio\tools\perf\run_awake.ps1"
$env:YUMEIREN_DIAG = "1"  # switch counting (T02) and diagnostics for every run

$results = @()

function Invoke-Scenario {
    param([string]$Playlist, [string]$OutCsv, [int]$DurationSec,
          [int]$AutoStopMs = 0, [int]$AutoStartMs = 0, [string]$Volume = "0",
          [string]$WasPlaying = "true", [string]$PauseFullscreen = "true")
    if (Test-Path $DiagLog) { Clear-Content $DiagLog -ErrorAction SilentlyContinue }
    & powershell -NoProfile -ExecutionPolicy Bypass -File $runAwake `
        -PlaylistCsv $Playlist -OutCsv $OutCsv -DurationSec $DurationSec `
        -AutoStopMs ([string]$AutoStopMs) -AutoStartMs ([string]$AutoStartMs) `
        -Volume $Volume -WasPlaying $WasPlaying -PauseFullscreen $PauseFullscreen | Out-Null
    # 保留每个用例的诊断日志用于失败取证
    if (Test-Path $DiagLog) {
        Copy-Item $DiagLog ($OutCsv -replace '\.csv$', '.log') -Force -ErrorAction SilentlyContinue
    }
}

function Get-Mean {
    param([string]$Csv, [string]$Column, [double]$From = 0, [double]$To = 1e9)
    if (-not (Test-Path $Csv)) { return -1 }
    $rows = Import-Csv $Csv | Where-Object {
        $_.private_mb -and [double]$_.elapsed_s -ge $From -and [double]$_.elapsed_s -le $To
    }
    if (-not $rows) { return -1 }
    $vals = @($rows | ForEach-Object { [double]$_.$Column } | Where-Object { $_ -ge 0 })
    if (-not $vals) { return -1 }
    return [math]::Round(($vals | Measure-Object -Average).Average, 1)
}

function Assert-Test {
    param([string]$Id, [string]$Csv, [bool]$Passed, [string]$Detail)
    $script:results += [pscustomobject]@{ Test = $Id; Passed = $Passed; Detail = $Detail; Csv = $Csv }
    $tag = if ($Passed) { "PASS" } else { "FAIL" }
    Write-Host "[$tag] $Id : $Detail"
}

function Test-PlaylistExists {
    param([string[]]$Files)
    foreach ($f in $Files) { if (-not (Test-Path $f)) { throw "missing test media: $f" } }
}

$inv = Join-Path $MediaRoot "inv"
$perf = Join-Path $MediaRoot "perf"
$good = Join-Path $inv "inv_1080p30.mp4"
$bad1 = Join-Path $inv "bad_truncated.mp4"
$bad2 = Join-Path $inv "bad_fake.mp4"
$noVideo = Join-Path $inv "audio_only.mp4"
$switchClips = (1..5 | ForEach-Object { Join-Path $perf "perf_switch$_.mp4" }) -join ";"
Test-PlaylistExists @($good, $bad1, $bad2, $noVideo) + (1..5 | ForEach-Object { Join-Path $perf "perf_switch$_.mp4" })

Write-Host "== T01 basic playback =="
$csv = Join-Path $OutDir "rt_t01_basic.csv"
Invoke-Scenario -Playlist $good -OutCsv $csv -DurationSec 70 -PauseFullscreen "false"
$gpu = Get-Mean -Csv $csv -Column "gpu_ded_mb" -From 30
$thr = Get-Mean -Csv $csv -Column "threads" -From 30
Assert-Test "T01 basic-play" $csv ($gpu -gt 100 -and $thr -gt 50) "gpu_ded=$gpu MB threads=$thr (expect >100 / >50)"

Write-Host "== T02 switch x30 (5 clips, 3 min) =="
$csv = Join-Path $OutDir "rt_t02_switch.csv"
Invoke-Scenario -Playlist $switchClips -OutCsv $csv -DurationSec 185 -PauseFullscreen "false"
$switches = 0
# 主日志可能被其他实例锁定而回退到按 PID 独立文件: 主+回退一并统计
$diagFiles = @($DiagLog)
$diagFiles += @(Get-ChildItem (Split-Path $DiagLog) -Filter "videowallpaper.log.*" -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName })
foreach ($f in $diagFiles) {
    if (Test-Path $f) {
        $switches += (Select-String -Path $f -Pattern "session=\d+ play index=" -AllMatches).Count
    }
}
$diagFiles | ForEach-Object { if (Test-Path $_) { Clear-Content $_ -ErrorAction SilentlyContinue } }
$gpu = Get-Mean -Csv $csv -Column "gpu_ded_mb" -From 30
Assert-Test "T02 switch-30" $csv ($switches -ge 30 -and $gpu -gt 100) "switches=$switches gpu_ded=$gpu MB"

Write-Host "== T03 stop -> reload =="
$csv = Join-Path $OutDir "rt_t03_reload.csv"
Invoke-Scenario -Playlist $good -OutCsv $csv -DurationSec 150 -AutoStopMs 60000 -AutoStartMs 90000 -PauseFullscreen "false"
$privIdle = Get-Mean -Csv $csv -Column "private_mb" -From 65 -To 88
$gpuBack = Get-Mean -Csv $csv -Column "gpu_ded_mb" -From 100
Assert-Test "T03 stop-reload" $csv ($privIdle -gt 0 -and $privIdle -lt 130 -and $gpuBack -gt 100) "stopped private=$privIdle MB (expect <130), reloaded gpu_ded=$gpuBack MB"

Write-Host "== T04 all-broken files =="
$csv = Join-Path $OutDir "rt_t04_allbroken.csv"
Invoke-Scenario -Playlist "$bad1;$bad2" -OutCsv $csv -DurationSec 60 -PauseFullscreen "false"
$gpuLate = Get-Mean -Csv $csv -Column "gpu_ded_mb" -From 30
Assert-Test "T04 all-broken" $csv ($gpuLate -eq 0) "late gpu_ded=$gpuLate MB (expect 0: bounded retries then stop)"

Write-Host "== T05 bad-then-good skip =="
$csv = Join-Path $OutDir "rt_t05_skip.csv"
Invoke-Scenario -Playlist "$bad1;$good" -OutCsv $csv -DurationSec 70 -PauseFullscreen "false"
$gpuLate = Get-Mean -Csv $csv -Column "gpu_ded_mb" -From 35
Assert-Test "T05 skip-bad" $csv ($gpuLate -gt 100) "late gpu_ded=$gpuLate MB (expect >100: skipped to good)"

Write-Host "== T06 audio-only skip =="
$csv = Join-Path $OutDir "rt_t06_novideo.csv"
Invoke-Scenario -Playlist "$noVideo;$good" -OutCsv $csv -DurationSec 90 -PauseFullscreen "false"
$gpuLate = Get-Mean -Csv $csv -Column "gpu_ded_mb" -From 45
$privLate = Get-Mean -Csv $csv -Column "private_mb" -From 45
Assert-Test "T06 no-video-track" $csv ($gpuLate -gt 100 -and $privLate -lt 470) "late gpu_ded=$gpuLate MB private=$privLate MB (stable playback, no churn growth)"

Write-Host "== T07 idle baseline =="
$csv = Join-Path $OutDir "rt_t07_idle.csv"
Invoke-Scenario -Playlist $good -OutCsv $csv -DurationSec 55 -WasPlaying "false"
$priv = Get-Mean -Csv $csv -Column "private_mb" -From 10
$ded = Get-Mean -Csv $csv -Column "gpu_ded_mb" -From 10
Assert-Test "T07 idle" $csv ($priv -gt 0 -and $priv -lt 130 -and $ded -eq 0) "private=$priv MB gpu_ded=$ded MB"

Write-Host ""
$pass = @($results | Where-Object { $_.Passed }).Count
Write-Host ("SUMMARY: {0}/{1} passed" -f $pass, $results.Count)
$results | Format-Table -AutoSize
if ($pass -lt $results.Count) { exit 1 }
